### ISSUE TITLE
PPF-1125: PdfReader object has no attribute `root_object`

### ISSUE THREAD

**Issue by pcraciunoiu** [chinapandaman/PyPDFForm#1125]
### Version

PyPDFForm=3.3.2

### Issue Description

After upgrading from 2.5.0 I get this error:

```
.venv/lib/python3.12/site-packages/PyPDFForm/wrapper.py", line 193, in _init_helper
    self._available_fonts.update(**get_all_available_fonts(self.read()))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.venv/lib/python3.12/site-packages/PyPDFForm/font.py", line 248, in get_all_available_fonts
    fonts = reader.root_object[AcroForm][DR][Font]

AttributeError: 'PdfReader' object has no attribute 'root_object'. Did you mean: 'get_object'?
```

### Code Snippet

```python
filled_pdf = PdfWrapper(file).fill(fields)
```

I tried in adobe_mode as well.

If I remove the check for available fonts, the generation works.

### PDF Form Template

Can't. It's confidential. But it works on 2.5.0. Seems to be broken since 3.0.0.

**Comment by chinapandaman** [comment]
Could you run pip freeze and let me know what version of pypdf are you on?
